print("Develop Versión 2.0")
print("En esta versión del software realizaremos cuentas más complejas")
print("Ingrese el primer valor a sumar: ")
num1 = input()
print("Ingrese el segundo valor a sumar: ")
num2 = input()
total = int(num1) + int(num2)
print("El valor de la suma es: " + str(total))